### ISSUE TITLE
New error with 'az ml model deploy' in 1.0.81

### ISSUE THREAD

**Issue by adiun** [Azure/azure-cli-extensions#1175]
### Extension name (the extension in question)

    "extensionType": "whl",
    "name": "azure-cli-ml",
    "version": "1.0.81"

### Description of issue (in as much detail as possible)

When running the following model deployment command, with `azure-cli-ml` 1.0.81 this is now throwing an error. This did not throw an error in `azure-cli-ml` 1.0.79.

`az ml model deploy -n quote-clf --inference-config-file src/inferconfig.json --auth-enabled true --deploy-config-file src/deployconfig_stab.json --compute-target aks-aml-stab -m quote_clf:3 -m quote_tfidf:3 --workspace-name aml-stab --resource-group aml-stab --overwrite -v`

**`src/inferconfig.json`**:

```json
{
    "condaFile": "environment.yaml",
    "enableGpu": false,
    "entryScript": "entry_script.py",
    "extraDockerfileSteps": "extra_dockerfile_steps",
    "runtime": "python",
    "sourceDirectory": "src"
}
```

**`src/deployconfig_stab.json`**:
```json
{
    "autoScaler": {
        "autoscaleEnabled": true,
        "minReplicas": 2,
        "maxReplicas": 4,
        "refreshPeriodInSeconds": 1,
        "targetUtilization": 70
    },
    "authEnabled": true,
    "computeType": "aks",
    "containerResourceRequirements": {
        "cpu": 1,
        "memoryInGB": 1
    },
    "enableAppInsights": true,
    "maxConcurrentRequestsPerContainer": 3,
    "maxQueueWaitMs": 5000,
    "scoringTimeoutMs": 120000
}
```

**`src/environment.yaml`**:
```yaml
name: quote
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=19.2.2
  - scikit-learn=0.20.3
  - spacy=2.1.7
  - pip:
      - azureml-defaults>=1.0.60
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz
```
