### ISSUE TITLE
Running az ml run submit-pipeline -y ml_pipeline.yml in an Azure Devops pipeline leads to an error: "ValueError: I/O operation on closed file"

### ISSUE THREAD

**Issue by marawanshalaby** [Azure/azure-cli-extensions#1629]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Azure CLI ML

### Description of issue (in as much detail as possible)
When running the `az ml run submit-pipeline -y ml_pipeline.yml` command  in an Azure Devops pipeline, the ML pipeline is submitted correctly to the  Azure ML service and runs successfully, however, the command still throws an error with the message:

![image](https://user-images.githubusercontent.com/45569036/80725436-5a0a2b00-8b03-11ea-983e-3025e7db1d55.png)

which leads to the devops pipeline failing. This same command works correctly locally, but it seems from the error message that there is some component redirecting the sys.stdout to a file and not redirecting it back

Using the `output_file` parameter also doesn't help

#### Devops pipeline task

```
    - task: AzureCLI@2
      displayName: 'Run Pipeline'
      inputs:
        azureSubscription: my-service-connection
        scriptLocation: inlineScript
        scriptType: 'pscore'
        inlineScript: |
          az ml run submit-pipeline --debug -n Train_Pipeline -y ./pipeline/ml_pipeline/ml_pipeline.yml
```

#### ML Pipeline

```
pipeline:
    name: Dispatcher_Train_Pipeline
    description: Pipeline for training and registering a model
    default_compute: cpucluster
    steps:
        Dataprep:
            type: "PythonScriptStep"
            name: "Prepare Data Step"
            compute: "cpucluster"
            script_name: "prepare_data.py"
            source_directory: "./pipeline_steps/prepare_data"
            allow_reuse: True
```

Azure CLI Version on Devops: 2.3.1 (that's the one that comes with both ubuntu-latest and windows-latest)

Azure CLI ML Version: 1.4.0
