### ISSUE TITLE
az ml run submit is inconsistent in using or ignoring the suffix '.runconfig' on a runconfig file. 

### ISSUE THREAD

**Issue by chrisfcarroll** [Azure/azure-cli-extensions#2346]
### Extension name (the extension in question)
ml

## az ml run submit won't create a computetarget using TensorFlow 

Consider the below runconfig file, which is mostly based on the one auto-generated by `az ml folder attach`.
It specifies  
- `framework: TensorFlow`
- `environment.name : AzureML-TensorFlow-2.2-GPU` <Taken from the AzureML curated environment list>

but the run finishes with the error shown below, indicating that the python script failed with ModuleNotFoundError: No module named 'tensorflow'

### Example 1
If I change 
```
script: train.py
```
to
```
script: anyotherfilename.py
```
The run fails, saying it can't find `train.py`

### Example 2

If I blank out the the key `environment.condaDependenciesFile`, and run from a folder attached to the workspace, it ignores the fact I blanked thekey and still picks up conda dependencies from `.azureml/conda_dependencies.yml`

I don't want Conda dependencies. I just want a working TensorFlow environment.

### Example 3
If I blank out the the key `environment.condaDependenciesFile`, and run from a folder **not** attached to the workspace, and with no .azureml directory, it fails with:
```
Conda dependencies were not specified.
```
I don't want Conda dependencies. I just want a working TensorFlow environment.

# runconfig file
```
# The script to run.
script: train.py
# The arguments to the script file.
arguments: []
# The name of the compute target to use for this run.
target: ml1
# Framework to execute inside. Allowed values are "Python" , "PySpark", "CNTK",  "TensorFlow", and "PyTorch".
framework: TensorFlow
# Communicator for the given framework. Allowed values are "None" ,  "ParameterServer", "OpenMpi", and "IntelMpi".
communicator: None
# Maximum allowed duration for the run.
maxRunDurationSeconds:
# Number of nodes to use for running job.
nodeCount: 1
# Environment details.
environment:
# Environment name
  name: AzureML-TensorFlow-2.2-GPU
# Environment version
  version:
# Environment variables set for the run.
  environmentVariables:
    EXAMPLE_ENV_VAR: EXAMPLE_VALUE
# Python details
  python:
# user_managed_dependencies=True indicates that the environmentwill be user managed. False indicates that AzureML willmanage the user environment.
    userManagedDependencies: false
# The python interpreter path
    interpreterPath: python
# Path to the conda dependencies file to use for this run. If a project
# contains multiple programs with different sets of dependencies, it may be
# convenient to manage those environments with separate files.
# was .azureml/conda_dependencies.yml
    condaDependenciesFile: 
# The base conda environment used for incremental environment creation.
    baseCondaEnvironment:
# Docker details
  docker:
# Probably has to be true. Set True to perform this run inside a Docker container.
    enabled: false
# Base image used for Docker-based runs. Mutually exclusive with base_dockerfile.
    baseImage: mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04:20200821.v1
# Base Dockerfile used for Docker-based runs. Mutually exclusive with base_image
    baseDockerfile:
# Set False if necessary to work around shared volume bugs.
    sharedVolumes: true
# Shared memory size for Docker container. Default is 2g.
    shmSize: 2g
# Extra arguments to the Docker run command.
    arguments: []
# Image registry that contains the base image.
    baseImageRegistry:
# DNS name or IP address of azure container registry(ACR)
      address:
# The username for ACR
      username:
# The password for ACR
      password:
# RegistryIdentity
      registryIdentity:
# Docker image platform
    platform:
# Operating System
      os: Linux
# Architecture
      architecture: amd64
# Spark details
  spark:
# List of spark repositories.
    repositories: []
# The packages to use.
    packages: []
# Whether to precache the packages.
    precachePackages: true
# Databricks details
  databricks:
# List of maven libraries.
    mavenLibraries: []
# List of PyPi libraries
    pypiLibraries: []
# List of RCran libraries
    rcranLibraries: []
# List of JAR libraries
    jarLibraries: []
# List of Egg libraries
    eggLibraries: []
# R details
  r:
# Inferencing stack version
  inferencingStackVersion:
# History details.
history:
# Enable history tracking -- this allows status, logs, metrics, and outputs
# to be collected for a run.
  outputCollection: true
# Whether to take snapshots for history.
  snapshotProject: true
# Directories to sync with FileWatcher.
  directoriesToWatch:
  - logs
# Spark configuration details.
spark:
# The Spark configuration.
  configuration:
    spark.app.name: Azure ML Experiment
    spark.yarn.maxAppAttempts: 1
# HDI details.
hdi:
# Yarn deploy mode. Options are cluster and client.
  yarnDeployMode: cluster
# Tensorflow details.
tensorflow:
# The number of worker tasks.
  workerCount: 1
# The number of parameter server tasks.
  parameterServerCount: 1
# Mpi details.
mpi:
# When using MPI, number of processes per node.
  processCountPerNode: 1
# ParallelTask details.
paralleltask:
# Maximum number of retries per worker. Default 0.
  maxRetriesPerWorker: 0
# The number of workers/processes per node. Default 1.
  workerCountPerNode: 1
# Worker exit codes to terminate job.
  terminalExitCodes:
# The configuration that describes how to make data available for the run.
# data reference configuration details
dataReferences: {}
# The configuration details for data.
data:
  example:
# Data Location
    dataLocation:
# the Dataset used for this run.
      dataset:
# Id of the dataset.
        id: d930ee50-ead4-4ed8-bf8b-5693dd691431
# the DataPath used for this run.
      datapath:
# Whether to create new folder.
    createOutputDirectories: false
# The mode to handle
    mechanism: mount
# Point where the data is download or mount or upload.
    environmentVariableName: mnist
# relative path where the data is download or mount or upload.
    pathOnCompute:
# Whether to overwrite the data if existing.
    overwrite: false
# The configuration that describes how to save and track outputs for the run
outputData: {}
# Project share datastore reference.
sourceDirectoryDataStore:
# AmlCompute details.
amlcompute:
# VM size of the Cluster to be created.Allowed values are Azure vm sizes.The list of vm sizes is available in 'https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-sizes-specs
  vmSize:
# VM priority of the Cluster to be created. Allowed values are:"dedicated" , "lowpriority".
  vmPriority:
# A bool that indicates if the cluster has to be retained after job completion.
  retainCluster: false
# Name of the cluster to be created. If not specified, runId will be used as cluster name.
  name: ml1
# Maximum number of nodes in the AmlCompute cluster to be created. Minimum number of nodes will always be set to 0.
  clusterMaxNodeCount:
```

# Error Result

```
Execution Summary
=================
RunId: ml1_1599945715_8211f6ca
Web View: https://ml.azure.com/experiments/ml1/runs/ml1_1599945715_8211f6ca?wsid=/subscriptions/3c751e5d-b46d-48a5-b66e-42a0a610221f/resourcegroups/ml1/workspaces/ml1

Warnings:
{
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "AzureMLCompute job failed.\nJobFailed: Submitted script failed with a non-zero exit code; see the driver log file for details.",
    "messageFormat": null,
    "messageParameters": null,
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": null
  },
  "correlation": {
    "operation": null,
    "request": "04d56e6197684b6e"
  },
  "environment": "uksouth",
  "location": "uksouth",
  "time": "2020-09-12T21:31:12.1340412+00:00",
  "componentName": "execution-worker"
}

ActivityFailedException:
	Message: Activity Failed:
{
    "error": {
        "code": "UserError",
        "message": "User program failed with ModuleNotFoundError: No module named 'tensorflow'",
        "detailsUri": "https://aka.ms/azureml-known-errors",
        "details": [],
        "debugInfo": {
            "type": "ModuleNotFoundError",
            "message": "No module named 'tensorflow'",
            "stackTrace": "  File \"/mnt/batch/tasks/shared/LS_root/jobs/ml1/azureml/ml1_1599945715_8211f6ca/mounts/workspaceblobstore/azureml/ml1_1599945715_8211f6ca/azureml-setup/context_manager_injector.py\", line 166, in execute_with_context\n    runpy.run_path(sys.argv[0], globals(), run_name=\"__main__\")\n  File \"/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/runpy.py\", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n  File \"/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"train.py\", line 3, in <module>\n    import tensorflow as tf\n"
        },
        "messageParameters": {}
    },
    "time": "0001-01-01T00:00:00.000Z"
}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with ModuleNotFoundError: No module named 'tensorflow'\",\n        \"detailsUri\": \"https://aka.ms/azureml-known-errors\",\n        \"details\": [],\n        \"debugInfo\": {\n            \"type\": \"ModuleNotFoundError\",\n            \"message\": \"No module named 'tensorflow'\",\n            \"stackTrace\": \"  File \\\"/mnt/batch/tasks/shared/LS_root/jobs/ml1/azureml/ml1_1599945715_8211f6ca/mounts/workspaceblobstore/azureml/ml1_1599945715_8211f6ca/azureml-setup/context_manager_injector.py\\\", line 166, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/azureml-envs/azureml_da3e97fcb51801118b8e80207f3e01ad/lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"train.py\\\", line 3, in <module>\\n    import tensorflow as tf\\n\"\n        },\n        \"messageParameters\": {}\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}"
    }
}
```
