### ISSUE TITLE
Azure ML CLI 2.0 - YAML config options

### ISSUE THREAD

**Issue by awcchungster** [Azure/azure-cli-extensions#3580]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

Azure Machine Learning

### Description of issue (in as much detail as possible)

-----

How do I define a YAML for an online endpoint that uses: 

Blob storage to store the model artifact pickle file. In my endpoint yaml, I have something similar to this, but I am being returned a Datastore ID error. 

```
deployments:
  - name: sklearn
    model:
      name: sklearn_1
      version: 1
      path: https://mlctldata.blob.core.windows.net/modelartifact/model.pkl
```

Similarly, is there a way to make the code configuration optional? As part of the container build process, I copy the code in the dockerfile. I could see why copying the code on runtime is more efficient, but I'd like to bypass that step in certain cases.
