### ISSUE TITLE
[containerapp] az is no longer creating appcontainer with yaml support

### ISSUE THREAD

**Issue by fargozhu** [Azure/azure-cli-extensions#4903]
## Describe the bug

When running 
```
az containerapp create -n kittens-in-hell -g rg-microservices-dev --environment platform --yaml containerapp.yaml
```

to create a containerapp using the declarative yaml file, I am getting the error `Invalid YAML provided. Please see https://aka.ms/azure-container-apps-yaml for a valid containerapps YAML spec.`

By comparing my yaml with the one documented by Microsoft [here](https://docs.microsoft.com/en-gb/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#container-app-examples), I cannot see any differences.

Furthermore, last week the same yaml was creating successfully an appcontainer, so...I am confused.

**Command Name**
`az containerapp create
Extension Name: containerapp. Version: 0.3.5.`

**Errors:**
```
Invalid YAML provided. Please see https://aka.ms/azure-container-apps-yaml for a valid containerapps YAML spec.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- make sure that both az and extensions versions are the same
```shell
❯ az version
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.5",
    "log-analytics": "0.2.2"
  }
}
```
- create a containerapp.yaml file, and then copy/paste. Make sure to replace the { } with valid data.
```yaml
kind: containerapp
location: westeurope
name: kittens-in-hell
resourceGroup: rg-microservices-dev
type: Microsoft.App/containerApps
properties:
  managedEnvironmentId: /subscriptions/{subscription_id}/resourceGroups/rg-microservices-dev/providers/Microsoft.App/managedEnvironments/platform
  configuration:
    activeRevisionsMode: Multiple
    secrets:
      - name: ghcrio
        value: {token}
    ingress:
      external: true
      allowInsecure: false
      targetPort: 8080
      traffic:
        - latestRevision: true
          weight: 100
      transport: Auto
    registries:
      - passwordSecretRef: ghcrio
        server: ghcr.io
        username: {username}
  template:
    revisionSuffix: myrevision
    containers:
      - image: "ghcr.io/{org}/kittens-in-hell:3.0.0"
        name: kittens-in-hell
        resources:
          cpu: 0.25
          memory: 0.5Gi
        probes:
          - type: liveness
            httpGet:
              - path: /healthz
                port: 8080
                httpHeaders:
                  - name: Custom-Header
                    value: liveness probe
                initialDelaySeconds: 7
                periodSeconds: 3
    scale:
      minReplicas: 1
      maxReplicas: 3
```
- `az containerapp create -n kittens-in-hell -g rg-microservices-dev --environment platform --yaml containerapp.yaml`

## Expected Behavior

Since the yaml was valid a week ago, my expectation is either to work correctly or at least to have a more explicit error message.

## Environment Summary
```
macOS-12.3.1-arm64-arm-64bit, Darwin 21.4.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0

Extensions:
log-analytics 0.2.2
containerapp 0.3.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
