### ISSUE TITLE
az ml online-deployment error "MissingDriverProgram"

### ISSUE THREAD

**Issue by franperezlopez** [Azure/azure-cli-extensions#5583]
## Describe the bug

**Command Name**
`az ml online-deployment create
Extension Name: ml. Version: 2.10.0.`

**Errors:**
```
(BadRequest) The request is invalid.
Code: BadRequest
Message: The request is invalid.
Exception Details:	(MissingDriverProgram) Could not find driver program in the request.
	Code: MissingDriverProgram
	Message: Could not find driver program in the request.
Additional Information:Type: ComponentName
Info: {
    "value": "managementfrontend"
}Type: Correlation
Info: {
    "value": {
        "operation": "86de0d2d85d2d0ee19f82e28b518c7ac",
        "request": "06d9fb8f6b1aebfc"
    }
}Type: Environment
Info: {
    "value": "northeurope"
}Type: Location
Info: {
    "value": "northeurope"
}Type: Time
Info: {
    "value": "2022-11-25T13:49:53.1312542+00:00"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- docker image built and pushed to ACR.azurecr.io/inference:v1
- file `online-deployment.yml`
```yaml
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: model-deployment
endpoint_name: model-endpoint
egress_public_network_access: disabled
model:
  path: ../model
  type: mlflow_model
environment_variables:
  MLFLOW_MODEL_FOLDER: ""
instance_type: Standard_DS3_v2
instance_count: 1
environment: 
  image: ACR.azurecr.io/inference:v1
```
- `az ml online-deployment create --all-traffic -n {} -f {}`

## Environment Summary
```
Linux-5.15.0-1017-azure-x86_64-with-glibc2.10, Ubuntu 20.04.5 LTS
Python 3.8.5
Installer: PIP

azure-cli 2.40.0 *

Extensions:
ml 2.10.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
Testing a vnet scenario, where the ACR and storage account are behind the vnet. Private endpoints are created accordingly.
Local deployment can be generated, but same deployment configuration and command, removing the `--local` parameter does not work out of the box.
It's not possible to reference the model using `azureml:model` syntax because I've got an error, so I need to use path format. Using `--local` I need to reference a single PKL file, but removing the `--local` parameter, I must use a folder (otherwise the CLI returns an explicit error requesting file / folder)
Could you please provide any insight about the "MissingDriverProgram" error?
