### ISSUE TITLE
az containerapp update : tcp support

### ISSUE THREAD

**Issue by merou** [Azure/azure-cli-extensions#6002]
## Description

When enabling Tcp transport and exposedPort in yaml deployment file - exposedPort is ignored. 

**Command Name**
`az containerapp update
Extension Name: containerapp. Version: 0.3.23.`

**Errors:**
```
n/a
```
## To Reproduce:

- `az containerapp update -n {} -g {} --yaml {}`

```yaml
...
...
    ingress:
      allowInsecure: false
      customDomains: null
      exposedPort: 9115
      external: true
      fqdn: xxxxxxx.wonderfulmeadow-91556248.westeurope.azurecontainerapps.io
      ipSecurityRestrictions: null
      targetPort: 9115
      traffic:
      - latestRevision: true
        weight: 100
      transport: Tcp
...
...
```

## Expected Behavior

exposedPort is set and visible in Azure Portal.

## Environment Summary
```
Linux-5.15.0-67-generic-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.46.0

Extensions:
containerapp 0.3.23
resource-graph 2.1.0
log-analytics 0.2.2
storage-preview 0.8.3
cloud-service 0.2.0
azure-devops 0.26.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
