### ISSUE TITLE
[az containerapp compose create] Docker Compose seems like not understand special variable: $AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN

### ISSUE THREAD

**Issue by vienleidl** [Azure/azure-cli-extensions#7631]
### Describe the bug

After run the _az containercompose create_ command with the following docker-compose file, the value of SERVER_HOST environment var hasn't been applied correctly. The result is SERVER_HOST => **nginx.** in Container App's environment variables.

```
version: '3.4'
services:
  app:
    image: 'ACR_NAME.azurecr.io/Repo_Name/Image_Name:Tag_Name'
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - SERVER_PROTOCOL=HTTP
      - SERVER_HOST=nginx.$AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN
      - SERVER_PORT=80
      - SERVER_PATH=/app

```

If it's updated as nginx.$$AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN => the result will be SERVER_HOST => nginx.$

### Related command

_az containercompose create_

### Errors

`##[error]time="2024-05-17T05:09:11Z" level=warning msg="The \"AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN\" variable is not set. Defaulting to a blank string."`

### Issue script & Debug output

`##[error]time="2024-05-17T05:09:11Z" level=warning msg="The \"AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN\" variable is not set. Defaulting to a blank string."`

### Expected behavior

```
template:
    containers:
    - env:
      - name: HOST
        value: 0.0.0.0
      - name: PORT
        value: '8080'
      - name: SERVER_PROTOCOL
        value: HTTP
      - name: SERVER_HOST
        value: nginx.xxxxxxxx-xxxxxxxx.southeastasia.azurecontainerapps.io
      - name: SERVER_PORT
        value: '80'
      - name: SERVER_PATH
        value: /app
```

### Environment Summary

```
{
  "azure-cli": "2.60.0",
  "azure-cli-core": "2.60.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "3.0.0b13",
    "azure-devops": "1.0.0",
    "containerapp": "0.3.50"
  }
}
```

### Additional context

Reference: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/accelerating-azure-container-apps-with-the-azure-cli-and-compose/ba-p/3516636#:~:text=There%20are%20also%20two%20special%20environment%20variables%20available%20at%20the%20time%20of%20evaluation%20that%20are%20specific%20to%20Azure%20Container%20Apps.%C2%A0%20AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN%C2%A0contains%20the%20default%20domain%20name%20for%20a%20Container%20Apps%20environment.
