### ISSUE TITLE
Support --allow-insecure option in az containerapp compose create command

### ISSUE THREAD

**Issue by vienleidl** [Azure/azure-cli-extensions#7632]
### Describe the bug

After run the _az container compose create_ command with the following docker-compose file, the Ingress has been enabled successfully with the correct protocol and target port. However, there is no option in docker-compose file to allow insecure connections.
```
version: '3.4'
services:
  app:
    image: 'ACR_NAME.azurecr.io/Repo_Name/Image_Name:Tag_Name'
    build:
      dockerfile: ./docker-compose/broker/Dockerfile
      args:
      - ATOKEN=${TOKEN:-default}
      context: ./..
    environment:
      - HOST=app.internal.$AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN
    expose:
    - 8080
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '1.0'
          memory: 2gb

```

### Related command

az containerapp compose create

### Errors

N/A

### Issue script & Debug output

N/A

### Expected behavior

There should be a configuration in the docker-compose file to allow insecure connections.

### Environment Summary

```
{
  "azure-cli": "2.60.0",
  "azure-cli-core": "2.60.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "3.0.0b13",
    "azure-devops": "1.0.0",
    "containerapp": "0.3.50"
  }
}
```
